version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: bullettrain
      POSTGRES_PASSWORD: password
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bin/docker
    environment:
      DJANGO_DB_NAME: bullettrain
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: password
      DJANGO_DB_PORT: 5432
      DJANGO_ALLOWED_HOSTS: localhost
      DJANGO_DB_HOST: db
    ports:
     - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
